//! Scaffold desktop and AgentBox manifests from curated templates.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail, ensure};
use clap::ValueEnum;
use serde::Serialize;

use crate::config;
use crate::state;

/// Kind of box to scaffold.
#[derive(Clone, Copy, Debug, PartialEq, Eq, ValueEnum, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum BoxKind {
    Desktop,
    Agent,
}

/// Language template for AgentBox manifests.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, ValueEnum, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AgentLang {
    #[default]
    Python,
    Node,
    Rust,
}

impl AgentLang {
    fn as_str(self) -> &'static str {
        match self {
            Self::Python => "python",
            Self::Node => "node",
            Self::Rust => "rust",
        }
    }
}

/// Options for [`scaffold`].
#[derive(Clone, Debug)]
pub struct InitOptions {
    pub kind: BoxKind,
    pub lang: AgentLang,
    pub name: Option<String>,
    pub force: bool,
    pub path: Option<PathBuf>,
}

/// Result of writing a scaffolded manifest.
#[derive(Clone, Debug, Serialize)]
pub struct InitResult {
    pub path: PathBuf,
    pub kind: BoxKind,
    pub template: String,
    pub name: String,
    pub overwritten: bool,
}

/// Write a curated manifest to disk without creating a container.
pub fn scaffold(options: InitOptions) -> Result<InitResult> {
    let default_name = match options.kind {
        BoxKind::Desktop => "devbox",
        BoxKind::Agent => "coding-agent",
    };
    let name = options
        .name
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .unwrap_or(default_name);
    ensure!(
        is_safe_name(name),
        "name {name:?} is invalid; use letters, digits, '.', '_', or '-', starting with alphanumeric"
    );

    let template = match options.kind {
        BoxKind::Desktop => "desktop-arch".to_string(),
        BoxKind::Agent => format!("agent-{}", options.lang.as_str()),
    };

    let path = options.path.unwrap_or_else(|| match options.kind {
        BoxKind::Desktop => PathBuf::from("devbox.yaml"),
        BoxKind::Agent => PathBuf::from("agentbox.yaml"),
    });
    let path = if path.as_os_str().is_empty() {
        bail!("output path must not be empty");
    } else {
        path
    };

    let overwritten = path.exists();
    if overwritten && !options.force {
        bail!(
            "{} already exists; pass --force to overwrite",
            path.display()
        );
    }
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("cannot create directory {}", parent.display()))?;
    }

    let body = render(options.kind, options.lang, name);
    // Validate before writing so a bad template never lands on disk.
    validate_template(&body, &path)?;
    state::atomic_write(&path, &body)
        .with_context(|| format!("cannot write {}", path.display()))?;

    Ok(InitResult {
        path,
        kind: options.kind,
        template,
        name: name.to_string(),
        overwritten,
    })
}

fn is_safe_name(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphanumeric() => {}
        _ => return false,
    }
    name.len() <= 128 && chars.all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
}

fn validate_template(body: &str, path: &Path) -> Result<()> {
    let dir = tempfile::tempdir().context("cannot create temporary directory")?;
    let temp = dir.path().join(
        path.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("manifest.yaml"),
    );
    std::fs::write(&temp, body).context("cannot write temporary manifest")?;
    config::load(&temp).context("scaffolded manifest failed validation")?;
    Ok(())
}

fn render(kind: BoxKind, lang: AgentLang, name: &str) -> String {
    match kind {
        BoxKind::Desktop => desktop_arch(name),
        BoxKind::Agent => match lang {
            AgentLang::Python => agent_python(name),
            AgentLang::Node => agent_node(name),
            AgentLang::Rust => agent_rust(name),
        },
    }
}

fn desktop_arch(name: &str) -> String {
    format!(
        r#"# Generated by `zaribox init --desktop`.
# Run: zaribox create {name}.yaml   (or pass this file path)

Name: {name}
Image: archlinux

# Optional: custom home directory (persists across recreations)
HomeDir: /home/$USER/Documents/{name}/

# Optional: mount host home directory at the same absolute path
HomeMount: true

Packages:
  - base-devel
  - git
  - neovim
  - starship
  - fish

# Optional: commands to run as your user after package install
Run:
  - echo 'exec fish' >> ~/.bashrc
  - mkdir -p ~/.config/fish && echo 'eval "$(starship init fish)"' >> ~/.config/fish/config.fish
"#
    )
}

fn agent_python(name: &str) -> String {
    format!(
        r#"# Generated by `zaribox init --agent --lang python`.
# Mount paths resolve relative to this file. Keep Source: . at the project root.
#
# Try:
#   zaribox validate {file}
#   zaribox create {file}
#   zaribox exec {name} -- python --version

ApiVersion: zaribox.dev/v1
Kind: AgentBox

Metadata:
  Name: {name}
  # Removed the next time `zaribox cleanup` runs after expiry.
  TTL: 1h
  Labels:
    purpose: coding-agent
    lang: python

Workspace:
  # AgentBox never mounts the host home. Every host path must be explicit.
  Mounts:
    - Source: .
      Target: /workspace
      ReadOnly: false
      Options:
        - nodev
        - nosuid

Runtime:
  # For reproducible automation, replace this tag with an image digest.
  Image: python:3.12
  Workdir: /workspace
  Packages:
    - git
  # Post-install commands run as the unprivileged AgentBox user.
  Run:
    - python --version
  Env:
    PYTHONDONTWRITEBYTECODE: "1"
    PIP_DISABLE_PIP_VERSION_CHECK: "1"

Resources:
  CPUs: 2
  Memory: 2GiB
  PidsLimit: 256

Security:
  Profile: agent
  # Package installation needs network. Use `none` with a prebuilt image.
  Network: slirp4netns
  Privileged: false
  ReadOnlyRootFilesystem: false
"#,
        file = "agentbox.yaml",
        name = name,
    )
}

fn agent_node(name: &str) -> String {
    format!(
        r#"# Generated by `zaribox init --agent --lang node`.
# Mount paths resolve relative to this file. Keep Source: . at the project root.
#
# Try:
#   zaribox validate agentbox.yaml
#   zaribox create agentbox.yaml
#   zaribox exec {name} -- node --version

ApiVersion: zaribox.dev/v1
Kind: AgentBox

Metadata:
  Name: {name}
  TTL: 1h
  Labels:
    purpose: coding-agent
    lang: node

Workspace:
  Mounts:
    - Source: .
      Target: /workspace
      ReadOnly: false
      Options:
        - nodev
        - nosuid

Runtime:
  Image: node:22
  Workdir: /workspace
  Packages:
    - git
  Run:
    - node --version
  Env:
    NODE_ENV: development

Resources:
  CPUs: 2
  Memory: 2GiB
  PidsLimit: 256

Security:
  Profile: agent
  Network: slirp4netns
  Privileged: false
  ReadOnlyRootFilesystem: false
"#
    )
}

fn agent_rust(name: &str) -> String {
    format!(
        r#"# Generated by `zaribox init --agent --lang rust`.
# Mount paths resolve relative to this file. Keep Source: . at the project root.
#
# Try:
#   zaribox validate agentbox.yaml
#   zaribox create agentbox.yaml
#   zaribox exec {name} -- rustc --version

ApiVersion: zaribox.dev/v1
Kind: AgentBox

Metadata:
  Name: {name}
  TTL: 1h
  Labels:
    purpose: coding-agent
    lang: rust

Workspace:
  Mounts:
    - Source: .
      Target: /workspace
      ReadOnly: false
      Options:
        - nodev
        - nosuid

Runtime:
  Image: rust:1-bookworm
  Workdir: /workspace
  Packages:
    - git
  Run:
    - rustc --version
  Env:
    CARGO_TERM_COLOR: always

Resources:
  CPUs: 2
  Memory: 2GiB
  PidsLimit: 256

Security:
  Profile: agent
  Network: slirp4netns
  Privileged: false
  ReadOnlyRootFilesystem: false
"#
    )
}

#[cfg(test)]
mod tests;
